/* eslint-disable no-unused-vars */
/**********************************************************************
 * Auto-generated by protocol-dts-generator.ts, do not edit manually. *
 **********************************************************************/

/**
 * The Chrome DevTools Protocol.
 * @public
 */

export type integer = number;
export * as Accessibility from './accessibility.d.ts'
export * as Animation from './animation.d.ts'
export * as Audits from './audits.d.ts'
export * as BackgroundService from './backgroundservice.d.ts'
export * as Browser from './browser.d.ts'
export * as CSS from './css.d.ts'
export * as CacheStorage from './cachestorage.d.ts'
export * as Cast from './cast.d.ts'
export * as DOM from './dom.d.ts'
export * as DOMDebugger from './domdebugger.d.ts'
export * as EventBreakpoints from './eventbreakpoints.d.ts'
export * as DOMSnapshot from './domsnapshot.d.ts'
export * as DOMStorage from './domstorage.d.ts'
export * as Database from './database.d.ts'
export * as DeviceOrientation from './deviceorientation.d.ts'
export * as Emulation from './emulation.d.ts'
export * as HeadlessExperimental from './headlessexperimental.d.ts'
export * as IO from './io.d.ts'
export * as IndexedDB from './indexeddb.d.ts'
export * as Input from './input.d.ts'
export * as Inspector from './inspector.d.ts'
export * as LayerTree from './layertree.d.ts'
export * as Log from './log.d.ts'
export * as Memory from './memory.d.ts'
export * as Network from './network.d.ts'
export * as Overlay from './overlay.d.ts'
export * as Page from './page.d.ts'
export * as Performance from './performance.d.ts'
export * as PerformanceTimeline from './performancetimeline.d.ts'
export * as Security from './security.d.ts'
export * as ServiceWorker from './serviceworker.d.ts'
export * as Storage from './storage.d.ts'
export * as SystemInfo from './systeminfo.d.ts'
export * as Target from './target.d.ts'
export * as Tethering from './tethering.d.ts'
export * as Tracing from './tracing.d.ts'
export * as Fetch from './fetch.d.ts'
export * as WebAudio from './webaudio.d.ts'
export * as WebAuthn from './webauthn.d.ts'
export * as Media from './media.d.ts'
export * as Console from './console.d.ts'
export * as Debugger from './debugger.d.ts'
export * as HeapProfiler from './heapprofiler.d.ts'
export * as Profiler from './profiler.d.ts'
export * as Runtime from './runtime.d.ts'
export * as Schema from './schema.d.ts'

